log_level: pinfo # info, debug, warn, pinfo, pdebug, pwarn, 
artifacts_path: 
  - dev
  - org 
m2_path: /Users/andrey/.m2/repository

repository_url: https://nexus.home.local
repository_name: maven-releases
token: dXNlcjpwYXNzd29yZA==